services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - redisnet

  redisinsight:
    image: "redis/redisinsight:latest"
    container_name: redisinsight
    ports:
      - 5540:5540
    depends_on:
      - redis
    networks:
      - redisnet

  queue-app:
    build:
      context: .
    container_name: queue-app
    ports:
      - "3000:3000"
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis  
    networks:
      - redisnet

volumes:
  redis_data:
    driver: local

networks:
  redisnet:
    driver: bridge
